#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_INPUT_REFERENCE    true

#define AUDIO_SPK_BCLK  GPIO_NUM_45
#define AUDIO_SPK_WS    GPIO_NUM_46
#define AUDIO_SPK_DOUT  GPIO_NUM_42

#define AUDIO_MIC_CLK   GPIO_NUM_38
#define AUDIO_MIC_DIN   GPIO_NUM_39


#define BUILTIN_LED_GPIO        GPIO_NUM_46
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC


#endif // _BOARD_CONFIG_H_
